### ISSUE TITLE
 Cannot redeclare class ci_exceptions

### ISSUE THREAD

**Issue by xm052359** [CodeIgniter-Chinese/CodeIgniter#12]
```
    our web application, sometime appearance Fatal  Cannot redeclare class ci_exceptions in XX.php ，but in this php has nothing contain ci_exceptions。Do you someone get this problems? thanks
```

**Comment by songxk** [comment]
please check it use this way of this blog "http://igaojie.com/webdev/222.html"
maybe it is the same reason

**Comment by Lamtin** [comment]
@songxk https://github.com/EllisLab/CodeIgniter/commits/develop

**Comment by songxk** [comment]
我想参与修改bug什么的 不知道有没有邮件组什么的

**Comment by songxk** [comment]
这个是谁都可以直接提交吗？

**Comment by songxk** [comment]
怎么可以加入呢

**Comment by Lamtin** [comment]
@songxk @CodeIgniter 你们把楼主忘了...

**Comment by songxk** [comment]
我已经回答了楼主的问题了 哈哈

**Comment by songxk** [comment]
谢谢LS的大姐姐

**Comment by Tengfei1010** [comment]
OK！

发自我的 iPad

在 2014-4-30，16:07，Hex notifications@github.com 写道：

**Comment by xm052359** [comment]
服务是小概率的出现这个问题，同样失败的请求我手动请求，不会浮现~
怎么加入ci中文社区哈？

**Comment by Tengfei1010** [comment]
我也想加入！
