### ISSUE TITLE
view can not get data!

### ISSUE THREAD

**Issue by snopein** [CodeIgniter-Chinese/CodeIgniter#2]
CI V2.1.3
PHP V5.2.5

<pre>
<code>
//controller------------------------------------------------------------------------------------
    public function index()
    {
        $data = array(
                'blog_title'   => 'My Blog Title',
                'blog_heading' => 'My Blog Heading',
                'blog_entries' => array(
                      array('title' => 'Title 1', 'body' => 'Body 1'),
                      array('title' => 'Title 2', 'body' => 'Body 2'),
                      array('title' => 'Title 3', 'body' => 'Body 3'),
                      array('title' => 'Title 4', 'body' => 'Body 4'),
                      array('title' => 'Title 5', 'body' => 'Body 5')
                 )
            );

         $this->load->view('welcome_message',$data);
    }
// END----------------------------------------------------------------------------------------
</code>
</pre>
 

<pre>
<code>
//view---------------------------------------------------------------------------------------

<?php print_r($data); ?>

//END--------------------------------------------------------------------------------------
</code>
</pre>

ERROR  Notice

A PHP Error was encountered

Severity: Notice

Message: Undefined variable: data

**Comment by Lamtin** [comment]
See
https://github.com/CodeIgniter-Chinese/CodeIgniter/blob/develop/system/core/Loader.php#L858
and
http://www.php.net/manual/en/function.extract.php

**Comment by snopein** [comment]
OH! Thank you very much, but why CodeIgniter Manual did not remind.

He should be added.

**Comment by Lamtin** [comment]
http://ellislab.com/codeigniter/user-guide/general/views.html

Let's try it with your controller file. Open it add this code:

```
<?php
class Blog extends CI_Controller {

        function index()
        {
            $data['title'] = "My Real Title";
            $data['heading'] = "My Real Heading";

            $this->load->view('blogview', $data);
        }
}
?>
```

Now open your view file and change the text to variables that correspond to the **array keys** in your data:

```
<html>
<head>
<title><?php echo $title;?></title>
</head>
<body>
    <h1><?php echo $heading;?></h1>
</body>
</html>
```
