### ISSUE TITLE
PHP如果使用了ZendGuadLoader后CI加载session类会导致服务器500错误

### ISSUE THREAD

**Issue by lwbbn** [CodeIgniter-Chinese/CodeIgniter#32]
如题，网站如加载了ZendGuadLoader后，CI使用$this->load->library('session')加载session类会导致服务器报错，错误代码500

PHP版本5.4.33  CI版本3.0

**Comment by tdutbky** [comment]
PHP.INI 中加载了Zend 就挂，去掉以下代码就正常。我也遇到同样的问题。

[Zend.loader]
zend_loader.enable=1
zend_loader.disable_licensing=0
zend_loader.obfuscation_level_support=3
zend_loader.license_path=
zend_extension="e:\php\ext\ZendLoader.dll"
