### ISSUE TITLE
CI libraries 加载语言文件错误。

### ISSUE THREAD

**Issue by lynxcat** [CodeIgniter-Chinese/CodeIgniter#5]
如果在config中配置了config['language'] = 'chinese'; 那么当发送email失败时。就会报错说加载不到语言文件。      英语水平很烂，就用中文了。盼复

**Comment by chekun** [comment]
你需要有相应的的语言文件的。

**Comment by lynxcat** [comment]
这个我明白，但是官方提供出来的类库。应该在加载自己需要的语言文件时指定好目录，不然我配置了$config['language']之后还得去把官方自带的语言文件夹拷贝一份。
