### ISSUE TITLE
 end(explode('.', $item)); is wrong

### ISSUE THREAD

**Issue by hyxj1220** [CodeIgniter-Chinese/CodeIgniter#6]
database\DB_active_rec.php line 224 "return end(explode('.', $item));" is wrong .because end() param must be array &$array

**Comment by chekun** [comment]
explode function will return an array , if $item is a valid string. what's your point?

**Comment by hyxj1220** [comment]
sorry  i'm english is poor ..end() funcion must be passed by reference, not passed by value,if you do that will be display notice wrong

**Comment by chekun** [comment]
没事，可以搞中文啊，懂你的意思了，你说的是对的。

**Comment by hyxj1220** [comment]
。。。恩 知道了

**Comment by chekun** [comment]
查了下源代码，开发分支已解决这个

https://github.com/EllisLab/CodeIgniter/blob/develop/system/database/DB_query_builder.php#L415

2.1分支依然是

https://github.com/EllisLab/CodeIgniter/blob/2.1-stable/system/database/DB_active_rec.php#L224

不过我用了这么久，一直没报这个错误，可能是我的php不是运行在strict mode下的 :sailboat:

**Comment by chekun** [comment]
@CodeIgniter 
![qq20131104-4](https://f.cloud.github.com/assets/1967804/1462381/1b7b8678-44f5-11e3-975a-4bff5521f285.png)
